// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Commit struct {
	Sha          string    `json:"sha"`
	RepositoryID int64     `json:"repository_id"`
	AuthorName   string    `json:"author_name"`
	AuthorEmail  string    `json:"author_email"`
	Message      string    `json:"message"`
	Url          string    `json:"url"`
	CommitDate   time.Time `json:"commit_date"`
	CreatedAt    time.Time `json:"created_at"`
}

type Repository struct {
	ID              int64              `json:"id"`
	GithubRepoID    int64              `json:"github_repo_id"`
	Owner           string             `json:"owner"`
	Name            string             `json:"name"`
	Description     string             `json:"description"`
	Url             string             `json:"url"`
	Language        string             `json:"language"`
	ForksCount      int32              `json:"forks_count"`
	StarsCount      int32              `json:"stars_count"`
	OpenIssuesCount int32              `json:"open_issues_count"`
	WatchersCount   int32              `json:"watchers_count"`
	RepoCreatedAt   time.Time          `json:"repo_created_at"`
	RepoUpdatedAt   time.Time          `json:"repo_updated_at"`
	LastSyncedAt    pgtype.Timestamptz `json:"last_synced_at"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
}
