// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateCommits(ctx context.Context, arg []CreateCommitsParams) (int64, error)
	CreateRepository(ctx context.Context, arg CreateRepositoryParams) (Repository, error)
	GetCommitsByRepoID(ctx context.Context, repositoryID int64) ([]Commit, error)
	GetLatestCommitDateForRepo(ctx context.Context, repositoryID int64) (pgtype.Timestamp, error)
	// internal/database/query.sql
	GetRepositoryByOwnerAndName(ctx context.Context, arg GetRepositoryByOwnerAndNameParams) (Repository, error)
	GetTopNCommitAuthors(ctx context.Context, arg GetTopNCommitAuthorsParams) ([]GetTopNCommitAuthorsRow, error)
	UpdateRepositorySyncData(ctx context.Context, arg UpdateRepositorySyncDataParams) (Repository, error)
}

var _ Querier = (*Queries)(nil)
