version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: github_fetcher_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: github_data
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d github_data"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: github_fetcher_app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8080:8080"

volumes:
  postgres_data: