// internal/syncer/syncer_test.go
package syncer

import (
	"context"
	"database/sql"
	"errors"
	"github.com/jackc/pgx/v5"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/mock"
	"log/slog"
	"os"
	"testing"

	"github-data-fetcher/internal/database"
	"github-data-fetcher/internal/model"
)

// MockQuerier is a mock implementation of the database.Querier interface.
// It is generated by testify/mock but could be hand-written as well.
type MockQuerier struct {
	mock.Mock
}

func (m *MockQuerier) GetRepositoryByOwnerAndName(ctx context.Context, params database.GetRepositoryByOwnerAndNameParams) (database.Repository, error) {
	args := m.Called(ctx, params)
	return args.Get(0).(database.Repository), args.Error(1)
}

func (m *MockQuerier) CreateRepository(ctx context.Context, params database.CreateRepositoryParams) (database.Repository, error) {
	args := m.Called(ctx, params)
	return args.Get(0).(database.Repository), args.Error(1)
}

func (m *MockQuerier) UpdateRepositorySyncData(ctx context.Context, params database.UpdateRepositorySyncDataParams) (database.Repository, error) {
	args := m.Called(ctx, params)
	return args.Get(0).(database.Repository), args.Error(1)
}

// Implement other Querier methods as needed, returning nil or zero values if they are not used in these tests.
func (m *MockQuerier) GetLatestCommitDateForRepo(ctx context.Context, repoID int64) (sql.NullTime, error) {
	return sql.NullTime{}, nil
}
func (m *MockQuerier) CreateCommits(ctx context.Context, arg []database.CreateCommitsParams) (int64, error) {
	return 0, nil
}
func (m *MockQuerier) GetTopNCommitAuthors(ctx context.Context, arg database.GetTopNCommitAuthorsParams) ([]database.GetTopNCommitAuthorsRow, error) {
	return nil, nil
}
func (m *MockQuerier) GetCommitsByRepoID(ctx context.Context, repoID int64) ([]database.Commit, error) {
	return nil, nil
}

func TestSyncer_UpsertRepository(t *testing.T) {
	logger := slog.New(slog.NewJSONHandler(os.Stdout, &slog.HandlerOptions{Level: slog.LevelDebug}))
	ctx := context.Background()

	// Sample input from GitHub client
	ghRepo := &model.Repository{
		GithubRepoID: 12345,
		Owner:        "test-owner",
		Name:         "test-repo",
		URL:          "http://example.com",
	}

	t.Run("creates a new repository if it does not exist", func(t *testing.T) {
		// Arrange
		mockDB := new(MockQuerier)
		syncer := &Syncer{db: mockDB, logger: logger}

		// Mock the GetRepositoryByOwnerAndName call to return "not found"
		mockDB.On("GetRepositoryByOwnerAndName", ctx, mock.Anything).Return(database.Repository{}, pgx.ErrNoRows).Once()

		// Expect CreateRepository to be called and define its return value
		expectedRepo := database.Repository{ID: 1, Owner: "test-owner", Name: "test-repo"}
		mockDB.On("CreateRepository", ctx, mock.Anything).Return(expectedRepo, nil).Once()

		// Act
		resultRepo, err := syncer.upsertRepository(ctx, ghRepo)

		// Assert
		assert.NoError(t, err)
		assert.Equal(t, expectedRepo, resultRepo)
		mockDB.AssertExpectations(t)
	})

	t.Run("updates an existing repository if it is found", func(t *testing.T) {
		// Arrange
		mockDB := new(MockQuerier)
		syncer := &Syncer{db: mockDB, logger: logger}

		// Mock the GetRepositoryByOwnerAndName call to return an existing repo
		existingRepo := database.Repository{ID: 1, Owner: "test-owner", Name: "test-repo"}
		mockDB.On("GetRepositoryByOwnerAndName", ctx, mock.Anything).Return(existingRepo, nil).Once()

		// Expect UpdateRepositorySyncData to be called and define its return value
		updatedRepo := database.Repository{ID: 1, Owner: "test-owner", Name: "test-repo", StarsCount: 100}
		mockDB.On("UpdateRepositorySyncData", ctx, mock.Anything).Return(updatedRepo, nil).Once()

		// Act
		resultRepo, err := syncer.upsertRepository(ctx, ghRepo)

		// Assert
		assert.NoError(t, err)
		assert.Equal(t, updatedRepo, resultRepo)
		mockDB.AssertExpectations(t)
		mockDB.AssertNotCalled(t, "CreateRepository") // Ensure create was NOT called
	})

	t.Run("returns an error if database lookup fails unexpectedly", func(t *testing.T) {
		// Arrange
		mockDB := new(MockQuerier)
		syncer := &Syncer{db: mockDB, logger: logger}
		dbError := errors.New("unexpected database error")

		// Mock the GetRepositoryByOwnerAndName call to return a generic error
		mockDB.On("GetRepositoryByOwnerAndName", ctx, mock.Anything).Return(database.Repository{}, dbError).Once()

		// Act
		_, err := syncer.upsertRepository(ctx, ghRepo)

		// Assert
		assert.Error(t, err)
		assert.Equal(t, dbError, err)
		mockDB.AssertExpectations(t)
		mockDB.AssertNotCalled(t, "CreateRepository")
		mockDB.AssertNotCalled(t, "UpdateRepositorySyncData")
	})
}
